package woorifisa.project.backend.domain.user.entity.enums;

public enum DocumentRejectionReasonCode {
	DOCUMENT_MISSING,
	DOCUMENT_UNREADABLE,
	DOCUMENT_CROPPED,
	DOCUMENT_NOT_OFFICIAL,
	DOCUMENT_ISSUE_DATE_MISSING,
	DOCUMENT_NAME_MISMATCH,
	DOCUMENT_EXPIRED,
	DOCUMENT_TYPE_MISMATCH,
	DOCUMENT_BOTH_SIDES_REQUIRED,

	RESIDENCE_ADDRESS_PAGE_MISSING,
	RESIDENCE_ADDRESS_MISSING,
	RESIDENCE_ADDRESS_INCOMPLETE,
	RESIDENCE_ISSUED_WITHIN_3_MONTHS_REQUIRED,
	RESIDENCE_REGISTRATION_NUMBER_MISSING,

	ALIEN_REGISTRATION_NUMBER_MISSING,
	ALIEN_REGISTRATION_NUMBER_UNREADABLE,
	ALIEN_REGISTRATION_APPLICATION_DATE_MISSING,
	ALIEN_REGISTRATION_AUTHORITY_MISSING,
	ALIEN_REGISTRATION_STATUS_MISSING,
	ALIEN_REGISTRATION_EXPIRY_MISSING
}
