server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  docker:
    compose:
      enabled: false

logging:
  level:
    root: info
    org.hibernate.SQL: debug

app:
  fds:
    base-url: ${FDS_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
