server:
  port: 9001
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  docker:
    compose:
      enabled: false

logging:
  level:
    root: info
    org.hibernate.SQL: warn

#app:
#  fds:
#    base-url: ${FDS_BASE_URL}
