import type { JobApplication, JobPostingDetail, JobRegion, PortfolioFile } from './types'

export const jobRegionLabels: Record<JobRegion, string> = {
  ALL: '전국',
  SEOUL: '서울',
  BUSAN: '부산',
  DAEGU: '대구',
  INCHEON: '인천',
  GWANGJU: '광주',
  DAEJEON: '대전',
  ULSAN: '울산',
  GYEONGGI: '경기',
}

export const jobRegions: JobRegion[] = [
  'ALL',
  'SEOUL',
  'BUSAN',
  'DAEGU',
  'INCHEON',
  'GWANGJU',
  'DAEJEON',
  'ULSAN',
  'GYEONGGI',
]

export const jobPostings: JobPostingDetail[] = [
  {
    jobId: 1,
    company: '행복한종합병원',
    region: 'SEOUL',
    openingTitle: '행복한종합병원 간호사(정규직) 모집',
    jobCategory: '간호/간호사',
    experience: '경력 2년 이상',
    employmentType: '정규직',
    salary: '연 3,200만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.20',
    recruitCount: 2,
    preferred: '종합병원 근무 경력자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '병동 간호 업무 및 환자 간호',
    workPeriod: '1년 이상',
    benefits: '4대보험, 퇴직연금, 연차, 경조금, 교육비 지원 등',
    address: '서울특별시 강남구 테헤란로 123',
    introduce:
      '행복한종합병원은 환자 중심의 최상의 의료서비스를 제공하며, 지역사회 건강 증진에 기여하는 종합병원입니다. 우수한 의료진과 최신 시설을 갖추고 함께 성장할 인재를 기다립니다.',
    responsibilities: ['병동 간호 업무 및 환자 간호', '진료 보조 및 검사 지원', '간호 기록 작성 및 관리', '환자 및 보호자 교육 및 상담'],
    qualifications: ['간호사 면허 소지자', '경력 2년 이상 (신입 지원 가능)', '책임감 있고 성실한 분', '원활한 커뮤니케이션 능력 보유자'],
    advantages: ['종합병원 근무 경력자 우대', '관련 자격증 소지자 우대', '장기근무 가능자 우대'],
    notices: ['허위사실이 발견될 경우 채용이 취소될 수 있습니다.', '국가유공자 및 장애인은 관련 법령에 의거 우대합니다.', '지원서 내용 중 허위사실이 있을 경우 합격이 취소될 수 있습니다.'],
  },
  {
    jobId: 2,
    company: '(주)미래테크',
    region: 'GYEONGGI',
    openingTitle: '(주)미래테크 백엔드 개발자 채용',
    jobCategory: 'IT/개발',
    experience: '경력 3년 이상',
    employmentType: '정규직',
    salary: '연 4,500만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.20',
    recruitCount: 1,
    preferred: 'Java/Spring 경험자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '백엔드 서비스 개발',
    workPeriod: '1년 이상',
    benefits: '점심 제공, 교육비 지원, 탄력근무',
    address: '경기도 성남시 분당구',
    introduce: '미래테크는 생활 금융 서비스를 만드는 IT 기업입니다.',
    responsibilities: ['REST API 개발', '서비스 운영 및 개선', '데이터 모델링'],
    qualifications: ['백엔드 개발 경력 3년 이상', 'Java 또는 Kotlin 사용 경험', '협업 도구 사용 경험'],
    advantages: ['Spring Boot 운영 경험', '금융 서비스 개발 경험', '클라우드 인프라 이해'],
    notices: ['포트폴리오 제출 시 우대합니다.', '면접 일정은 개별 안내됩니다.'],
  },
  {
    jobId: 3,
    company: '바다마을',
    region: 'BUSAN',
    openingTitle: '바다마을 해운사무직 사원 모집',
    jobCategory: '사무/경리',
    experience: '신입/경력',
    employmentType: '정규직',
    salary: '연 2,800만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.19',
    recruitCount: 3,
    preferred: '문서 작성 능숙자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '해운 사무 및 경리 업무',
    workPeriod: '6개월 이상',
    benefits: '4대보험, 식대 지원',
    address: '부산광역시 중구 중앙대로',
    introduce: '바다마을은 해운 물류 사무를 전문으로 하는 회사입니다.',
    responsibilities: ['해운 문서 정리', '거래처 응대', '정산 자료 관리'],
    qualifications: ['기본 문서 작성 가능자', '성실하고 꼼꼼한 분'],
    advantages: ['영어 가능자 우대', '관련 업무 경험자 우대'],
    notices: ['수습기간이 있을 수 있습니다.'],
  },
  {
    jobId: 4,
    company: '늘푸른 요양원',
    region: 'DAEGU',
    openingTitle: '늘푸른 요양원 사회복지사 모집',
    jobCategory: '복지/사회복지',
    experience: '경력 1년 이상',
    employmentType: '계약직',
    salary: '연 2,600만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.19',
    recruitCount: 1,
    preferred: '요양시설 근무 경험자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '입소자 상담 및 프로그램 운영',
    workPeriod: '1년',
    benefits: '4대보험, 명절 상여',
    address: '대구광역시 수성구',
    introduce: '늘푸른 요양원은 어르신의 안정적인 생활을 지원합니다.',
    responsibilities: ['상담 기록 관리', '복지 프로그램 운영', '보호자 상담'],
    qualifications: ['사회복지사 자격증 소지자', '경력 1년 이상'],
    advantages: ['장기요양기관 근무 경험', '운전 가능자'],
    notices: ['계약 종료 후 정규직 전환 검토가 가능합니다.'],
  },
  {
    jobId: 5,
    company: '(주)하늘항공',
    region: 'INCHEON',
    openingTitle: '(주)하늘항공 객실승무원 채용',
    jobCategory: '서비스/승무원',
    experience: '신입/경력',
    employmentType: '정규직',
    salary: '연 3,000만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.18',
    recruitCount: 5,
    preferred: '외국어 가능자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '객실 서비스 및 안전 관리',
    workPeriod: '1년 이상',
    benefits: '항공권 지원, 유니폼 지급',
    address: '인천광역시 중구 공항로',
    introduce: '하늘항공은 안전하고 편안한 항공 서비스를 제공합니다.',
    responsibilities: ['기내 서비스', '승객 안전 안내', '비상 상황 대응'],
    qualifications: ['서비스 마인드 보유자', '해외여행 결격 사유가 없는 분'],
    advantages: ['영어/중국어/일본어 가능자', '서비스업 경험자'],
    notices: ['신체검사 및 교육 과정이 포함됩니다.'],
  },
  {
    jobId: 6,
    company: '디자인스튜디오',
    region: 'SEOUL',
    openingTitle: '디자인스튜디오 아트디자이너 모집',
    jobCategory: '디자인',
    experience: '경력 2년 이상',
    employmentType: '정규직',
    salary: '연 3,200만원 이상',
    workDays: '주5일',
    createdAt: '2024.05.18',
    recruitCount: 1,
    preferred: '브랜딩 프로젝트 경험자 우대',
    age: '무관',
    gender: '무관',
    jobRole: '브랜드 디자인 및 콘텐츠 제작',
    workPeriod: '1년 이상',
    benefits: '장비 지원, 교육비 지원',
    address: '서울특별시 마포구',
    introduce: '디자인스튜디오는 다양한 브랜드의 시각 경험을 만듭니다.',
    responsibilities: ['브랜드 디자인', 'SNS 콘텐츠 제작', '디자인 가이드 관리'],
    qualifications: ['디자인 툴 사용 가능자', '포트폴리오 제출 가능자'],
    advantages: ['브랜딩 경험', '모션 그래픽 경험'],
    notices: ['포트폴리오 제출은 필수입니다.'],
  },
]

export const portfolioFiles: PortfolioFile[] = [
  {
    fileId: 1,
    fileName: '조수재 포인터 이력서.pdf',
    fileType: 'RESUME',
    createdAt: '2024.05.20',
    version: 'v1.2',
    pageCount: 5,
  },
  {
    fileId: 2,
    fileName: '조수재 포트폴리오.pdf',
    fileType: 'PORTFOLIO',
    createdAt: '2024.03.15',
    version: 'v1.0',
    pageCount: 3,
  },
]

export const jobApplications: JobApplication[] = [
  {
    applicationId: 1,
    jobId: 1,
    openingTitle: '간호사 채용 공고',
    status: 'PASSED',
    company: '행복한종합병원',
    createdAt: '2026년 06월 12일',
    files: [portfolioFiles[0]],
  },
  {
    applicationId: 2,
    jobId: 7,
    openingTitle: '피부과 상담실장 모집',
    status: 'FAILED',
    company: '맑은피부의원',
    createdAt: '2026년 06월 18일',
    files: [portfolioFiles[1]],
  },
  {
    applicationId: 3,
    jobId: 8,
    openingTitle: '약국 조제사 경력직 채용',
    status: 'UNREAD',
    company: '온누리약국',
    createdAt: '2026년 06월 25일',
    files: [portfolioFiles[0], portfolioFiles[1]],
  },
  {
    applicationId: 4,
    jobId: 9,
    openingTitle: '가정의학과 간호조무사 채용',
    status: 'READ',
    company: '우리동네의원',
    createdAt: '2026년 07월 02일',
    files: [portfolioFiles[0]],
  },
]
