server:
  port: 9000
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  docker:
    compose:
      enabled: false

logging:
  level:
    root: info
    org.hibernate.SQL: warn

app:
  core-banking:
    base-url: ${ONPREM_GATEWAY_BASE_URL}
  government:
    base-url: ${ONPREM_GATEWAY_BASE_URL}
  ai:
    base-url: ${AI_BASE_URL}
